add cool sound asmr
3kh0/soundboard pull request #3
Opened 2023-09-25 22:31 UTC by UpTiGamer

2023-09-26 17:59 UTC, 3kh0 requested changes
Rename the sound file so it does not have spaces, sometimes it will mess things up

2023-09-26 18:08 UTC, UpTiGamer commented
@3kh0 i do

2023-12-16 01:51 UTC, UpTiGamer commented
@3kh0 add

2023-12-16 16:34 UTC, 3kh0 approved these changes

2023-12-16 16:34 UTC, merged